version: '3.7'
services:
  openjdk-8:
    image: repository.dimas-maryanto.com:8086/openjdk:8-alpine
    environment:
      - APPLICATION_PORT=8080
    ports:
      - 8080:8080
    entrypoint:
      - "java"
      - '-jar'
      - "-Djava.security.egd=file:/dev/./urandom"
      - "/var/applications/application.jar"
    networks:
      - openjdk_network
networks:
  openjdk_network:
