version: '3.7'
services: 
    elastic-agent:
        image: ${PRIVATE_REPOSITORY}beats/elastic-agent:${ELASTICSEARCH_VERSION}
        depends_on: 
            - ${ELASTICSEARCH_HOST}
        networks:
            - elastic_network
networks:
    elastic_network: