version: '3.7'
services: 
    filebeat:
        image: ${PRIVATE_REPOSITORY}beats/filebeat:${ELASTICSEARCH_VERSION}
        depends_on: 
            - ${ELASTICSEARCH_HOST}
        networks:
            - elastic_network
networks:
    elastic_network: