version: '3.7'
services: 
    heartbeat:
        image: ${PRIVATE_REPOSITORY}beats/heartbeat:${ELASTICSEARCH_VERSION}
        depends_on: 
            - ${ELASTICSEARCH_HOST}
        networks:
            - elastic_network
networks:
    elastic_network: