version: '3.7'
services: 
    metricbeat:
        image: ${PRIVATE_REPOSITORY}beats/metricbeat:${ELASTICSEARCH_VERSION}
        depends_on: 
            - ${ELASTICSEARCH_HOST}
        networks:
            - elastic_network
networks:
    elastic_network: