version: '3.7'
services:
  reactivedb:
    image: ${PRIVATE_REPOSITORY}mongo:${MONGO_VERSION}
    networks:
      - monggo-network
    ports:
      - 27017:${MONGO_PORT}
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - monggo-data:/data/db
networks:
  monggo-network:
volumes:
  monggo-data:
