version: '3.7'
services:
  sqlserver:
    image: ${PRIVATE_REPOSITORY}mssql/server:${MSSQL_VERSION}
    environment:
      - ACCEPT_EULA
      - SA_PASSWORD
      - MSSQL_PID
    ports:
      - 1433:${MSSQL_PORT}
    volumes:
      - sqlserver_data:/var/opt/mssql/
    networks:
      - sqlserver-network
networks:
  sqlserver-network:
volumes:
  sqlserver_data:
