version: '3.7'
services:
  activemq:
    image: ${PRIVATE_REPOSITORY}webcenter/activemq:${ACTIVEMQ_VERSION}
    environment:
      - ACTIVEMQ_CONFIG_MINMEMORY
      - ACTIVEMQ_CONFIG_MAXMEMORY
      - ACTIVEMQ_ADMIN_LOGIN
      - ACTIVEMQ_ADMIN_PASSWORD
    ports:
      - 8161:8161
      - 1883:1883
      - 61616:61616
      - 61614:61614
    volumes:
      - ./conf/:/opt/activemq/conf/
    networks:
      - activemq-network
networks:
  activemq-network: