version: '3.7'
services:
  nginx:
    image: repository.dimas-maryanto.com:8086/nginx:1.17.3
    ports:
      - 80:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx-network
networks:
  nginx-network:
