version: '3.7'
services:
  nginx:
    image: ${PRIVATE_REPOSITORY}nginx:${NGINX_VERSION}
    ports:
      - 80:${NGINX_PORT}
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx-network
networks:
  nginx-network:
