version: '3.7'
services:
  oracle:
    image: ${PRIVATE_REPOSITORY}oracle/database:18.4.0-xe
    ports:
      - 1521:1521
      - 5500:8080
    environment:
      - ORACLE_PWD
    shm_size: 1g
    volumes:
      - ./oracle/setup/:/opt/oracle/scripts/setup
      - ./oracle/startup:/opt/oracle/scripts/startup
      - oracle-data:/opt/oracle/oradata
    networks:
      - oracle-network
volumes:
  oracle-data:
networks:
  oracle-network:
