version: '3.7'
services:
  mysql:
    image: repository.dimas-maryanto.com:8086/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=example
      - MYSQL_PASSWORD=example
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network
volumes:
  mysql_data:
networks:
  mysql_network:
