version: '3.7'
services:
  postgres:
    image: ${PRIVATE_REPOSITORY}postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_HOST_AUTH_METHOD
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-network
volumes:
  postgres_data:
networks:
  postgres-network:
